# Generated by Django 3.1.4 on 2021-01-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_rezervari'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervari',
            name='nume',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezervari',
            name='prenume',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
